module_chapitre_cours_homepage:
    path:     /Matiere/{id}/Modules
    defaults: { _controller: ModuleChapitreCoursBundle:Module:index }
module_chapitre_cours_stats:
    path:     /Matiere/{id}/Modules/stats
    defaults: { _controller: ModuleChapitreCoursBundle:Module:stat }

module_chapitre_coursf_homepage:
    path:     /Module/{id}/Chapitres
    defaults: { _controller: ModuleChapitreCoursBundle:Chapitre:index }

chapitre_delete:
    path:     /Chapitre/{id}/{lastid}
    defaults: { _controller: ModuleChapitreCoursBundle:Chapitre:del }

module_delete:
    path:     /Module/{id}/{lastid}
    defaults: { _controller: ModuleChapitreCoursBundle:Module:del }

cours_add:
    path:     /cours/add
    defaults: { _controller: ModuleChapitreCoursBundle:Cours:add }
cours_list:
    path:     /cours/list
    defaults: { _controller: ModuleChapitreCoursBundle:Cours:list }
cours_del:
    path:     /cours/{id}/delete
    defaults: { _controller: ModuleChapitreCoursBundle:Cours:del }
