gestion_niveaux:
  resource: "@GestionNiveauxBundle/Resources/config/routing.yml"
  prefix:   /
mail:
  resource: "@MailBundle/Resources/config/routing.yml"
  prefix:   /mail

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /users

app:
    resource: '@AppBundle/Controller/'
    type: annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


