utilisateurs_homepage:
    path:     /this
    defaults: { _controller: UtilisateursBundle:Default:index }

niveau_homepage:
  path:     ecole/niveau
  defaults: { _controller: GestionNiveauxBundle:niveau:niveau }

deleteNiveau:
  path:     ecole/niveau/{id}
  defaults: { _controller: GestionNiveauxBundle:niveau:deleteNiveau }


createNiveau:
  path:     ecole/createNiveau
  defaults: { _controller: GestionNiveauxBundle:niveau:createNiveau }


updateNiveau:
  path:     /updateNiveau/{id}
  defaults: { _controller: GestionNiveauxBundle:niveau:updateNiveau }


searchNiveau:
  path:     /searchNiveau
  defaults: { _controller: GestionNiveauxBundle:niveau:searchNiveau }




matiere_homepage:
  path:     ecole/matiere/{id}
  defaults: { _controller: GestionNiveauxBundle:matiere:matiere }

createMatiere:
  path:     /createMatiere/{id}
  defaults: { _controller: GestionNiveauxBundle:matiere:createMatiere }

deleteMatiere:
  path:     /deleteMatiere/{id}
  defaults: { _controller: GestionNiveauxBundle:matiere:deleteMatiere }

updateMatiere:
  path:     /updateMatiere/{id}
  defaults: { _controller: GestionNiveauxBundle:matiere:updateMatiere }





etudiant_homepage:
    path:     ecole/etudiant
    defaults: { _controller: UtilisateursBundle:Default:etudiant }


professor_homepage:
    path:     ecole/professeur
    defaults: { _controller: UtilisateursBundle:Default:professor }

createProfesseur:
    path:     ecole/createProfesseur
    defaults: { _controller: UtilisateursBundle:Default:createProfesseur }

deleteProfesseur:
  path:     ecole/deleteProfesseur/{id}
  defaults: { _controller: UtilisateursBundle:Default:deleteProfesseur }

updateProfesseur:
  path:     ecole/updateProfesseur/{id}
  defaults: { _controller: UtilisateursBundle:Default:updateProfesseur }

professeur_search:
  path:     ecole/searchProfesseur
  defaults: { _controller: UtilisateursBundle:Default:searchProfesseur }


professeur_search_ajax:
  path:     ecole/searchProfesseurAjax
  defaults: { _controller: UtilisateursBundle:Default:searchProfesseurAjax}


professeur_search_matiere:
  path:     ecole/searchProfesseurByMatiere
  defaults: { _controller: UtilisateursBundle:Default:searchProfesseurByMatiere }



createEtudiant:
  path:     ecole/createEtudiant
  defaults: { _controller: UtilisateursBundle:Default:createEtudiant }


deleteEtudiant:
  path:     ecole/deleteEtudiant/{id}
  defaults: { _controller: UtilisateursBundle:Default:deleteEtudiant }

updateEtudiant:
  path:     ecole/updateEtudiant/{id}
  defaults: { _controller: UtilisateursBundle:Default:updateEtudiant }

etudiant_search:
  path:     ecole/searchEtudiant
  defaults: { _controller: UtilisateursBundle:Default:searchEtudiant }

etudiant_search_classe:
  path:     ecole/searchEtudiantByClasse
  defaults: { _controller: UtilisateursBundle:Default:searchEtudiantByClasse }


etudiant_search_ajax:
  path:     ecole/searchEtudiantAjax
  defaults: { _controller: UtilisateursBundle:Default:searchEtudiantAjax}








classe_homepage:
  path:     ecole/classe/{id}
  defaults: { _controller: GestionNiveauxBundle:classe:classe }

createClasse:
  path:     /createClasse/{id}
  defaults: { _controller: GestionNiveauxBundle:classe:createClasse }

deleteClasse:
  path:     /deleteClasse/{id}
  defaults: { _controller: GestionNiveauxBundle:classe:deleteClasse }

updateClasse:
  path:     /updateClasse/{id}
  defaults: { _controller: GestionNiveauxBundle:classe:updateClasse }


ecole_home:
  path:     ecole/home
  defaults: { _controller: UtilisateursBundle:Default:showEcole }


etudiant_home:
  path:     etudiant/home
  defaults: { _controller: UtilisateursBundle:Default:showEtudiant }


professeur_home:
  path:     professeur/home
  defaults: { _controller: UtilisateursBundle:Default:showProfesseur }







redirect:
  path:     redirect
  defaults: { _controller: UtilisateursBundle:Default:redirect }


chart:
  path:     ecole/chart
  defaults: { _controller: UtilisateursBundle:Default:chart }






